/**
 * Database schema type definitions for Kysely
 * These types provide compile-time type safety for all database queries
 */

import type { Generated, ColumnType } from 'kysely';

/**
 * Earthquake record from USGS or other sources
 */
export interface EarthquakeTable {
  // Primary key (auto-generated)
  id: Generated<number>;

  // Time of the earthquake (partition key for TimescaleDB)
  time: ColumnType<Date, Date | string, Date | string>;

  // Source tracking
  source: string;                    // 'USGS', 'EMSC', etc.
  source_event_id: string;           // Original ID from source (e.g., 'us7000abc1')

  // Location
  latitude: number;
  longitude: number;
  // Note: 'location' GEOGRAPHY column is auto-generated by PostGIS, not inserted directly
  depth_km: number | null;

  // Magnitude
  magnitude: number;
  magnitude_type: string | null;     // 'ml', 'mb', 'mw', etc.

  // Metadata
  place: string | null;              // Human-readable location
  status: string | null;             // 'reviewed', 'automatic'
  tsunami_warning: boolean;
  felt_reports: number | null;       // Number of "Did You Feel It?" reports
  cdi: number | null;                // Community Decimal Intensity
  mmi: number | null;                // Modified Mercalli Intensity
  alert: string | null;              // PAGER alert level: 'green', 'yellow', 'orange', 'red'

  // Multi-source deduplication (future)
  canonical_event_id: number | null;
  is_canonical: boolean;

  // Audit timestamps
  created_at: Generated<Date>;
  updated_at: Generated<Date>;
}

/**
 * Sync status tracking
 */
export interface SyncStatusTable {
  id: Generated<number>;
  source: string;
  last_sync_time: Date;
  last_event_time: Date | null;
  events_synced: number;
  status: 'success' | 'error' | 'running';
  error_message: string | null;
  created_at: Generated<Date>;
}

/**
 * Complete database schema
 */
export interface Database {
  earthquakes: EarthquakeTable;
  sync_status: SyncStatusTable;
}
